export const FETCH_AUTHORS = "FETCH_AUTHORS";
export const FILTER_AUTHORS = "FILTER_AUTHORS";
export const FETCH_AUTHOR_DETAIL = "FETCH_AUTHOR_DETAIL";
export const FETCH_BOOKS = "FETCH_BOOKS";
export const BOOKS = "FILTER_BOOKS";
